version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: logiglo_backend_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: logiglo
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: logiglo_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U logiglo_backend_postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
